version: 2

project_name: datatug

before:
  hooks:
    - go mod tidy

builds:
  - id: datatug-unix
    main: .
    binary: datatug
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: datatug-windows
    main: .
    binary: datatug
    env: [ CGO_ENABLED=0 ]
    goos: [ windows ]
    goarch: [ amd64 ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: tarball
    formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ datatug-unix ]
    files:
      - README.md
      - LICENSE*

  - id: zip
    formats: [ zip ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ datatug-windows ]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: datatug
    name: datatug-cli

brews:
  - name: datatug
    description: "DataTug – versioned database and project validator"
    homepage: https://github.com/datatug/datatug-cli
    license: MIT

    repository:
      owner: datatug
      name: homebrew-tap

    binary: datatug

    install: |
      bin.install "datatug"

    test: |
      system "#{bin}/datatug", "--version"
